//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JavaFlorist.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CART
    {
        public int CARTID { get; set; }
        public int CUSTID { get; set; }
        public int BOUQUETID { get; set; }
        public int QUANTITY { get; set; }
    
        public virtual BOUQUET BOUQUET { get; set; }
        public virtual CUSTOMER CUSTOMER { get; set; }
    }
}
