//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JavaFlorist.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ORDER
    {
        public int ORDERID { get; set; }
        public int CUSTID { get; set; }
        public int OCCASIONID { get; set; }
        public int BOUQUETID { get; set; }
        public string ORDERNAME { get; set; }
        public string ORDERADDRESS { get; set; }
        public string ORDERPHONE { get; set; }
        public System.DateTime ORDERDATE { get; set; }
        public int QUANTITY { get; set; }
        public double TOTALPRICE { get; set; }
    
        public virtual BOUQUET BOUQUET { get; set; }
        public virtual CUSTOMER CUSTOMER { get; set; }
        public virtual OCCASION OCCASION { get; set; }
    }
}
